sonar.projectKey=Imagenation
sonar.projectName=Imagenation
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/test/**,**/coverage/**
sonar.host.url=http://localhost:9000
sonar.login=sqp_721cbf6c8b3aefff4143a56bfd982ecb4749115d 